"""empty message

Revision ID: 83c8a27837dd
Revises: f6a34e8dae65
Create Date: 2026-01-18 10:11:55.692219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c8a27837dd'
down_revision = 'f6a34e8dae65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_symbol', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_column('stock_symbol')

    # ### end Alembic commands ###
